language: csharp
mono: none
dotnet: 3.1
solution: friendly_jigger.sln
script:
  - dotnet restore
  - dotnet publish -c Release -r win10-x64
  - ls -alh friendly_jigger/bin/Release/netcoreapp3.1/win10-x64/publish/
deploy:
  provider: releases
  api_key: $DEPLOY_TOKEN
  file: 
    - "./friendly_jigger/bin/Release/netcoreapp3.1/win10-x64/publish/friendly_jigger.exe"
  skip_cleanup: true
  draft: true
  #on:
  #  tags: true