os: linux
language: csharp
mono: none
dotnet: 5.0
solution: friendly_jigger.sln
script:
  #- [[ "$TRAVIS_TAG" == "" ]] && PROJ_VER=$TRAVIS_BUILD_NUMBER || PROJ_VER=$TRAVIS_TAG
  - printenv
  - export PROJ_VERSION=$TRAVIS_BUILD_NUMBER
  - echo "Project version is $PROJ_VER"
  - dotnet publish -c Release -r win10-x64 /p:Version=$PROJ_VER
  - dotnet publish -c Release -r linux-x64 /p:Version=$PROJ_VER
  - mv "./friendly_jigger/bin/Release/net5.0/linux-x64/publish/friendly_jigger" "./friendly_jigger/bin/Release/net5.0/linux-x64/publish/friendly_jigger_linux"
  - dotnet publish -c Release -r osx-x64 /p:Version=$PROJ_VER
  - mv "./friendly_jigger/bin/Release/net5.0/osx-x64/publish/friendly_jigger" "./friendly_jigger/bin/Release/net5.0/osx-x64/publish/friendly_jigger_mac"

deploy:
  - provider: releases
    token: $DEPLOY_TOKEN
    file: 
      - "./friendly_jigger/bin/Release/net5.0/win10-x64/publish/friendly_jigger.exe"
      - "./friendly_jigger/bin/Release/net5.0/linux-x64/publish/friendly_jigger_linux"
      - "./friendly_jigger/bin/Release/net5.0/osx-x64/publish/friendly_jigger_mac"
    draft: true
    overwrite: true
    skip_cleanup: true
    on:
      tags: false

  - provider: releases
    token: $DEPLOY_TOKEN
    file: 
      - "./friendly_jigger/bin/Release/net5.0/win10-x64/publish/friendly_jigger.exe"
      - "./friendly_jigger/bin/Release/net5.0/linux-x64/publish/friendly_jigger_linux"
      - "./friendly_jigger/bin/Release/net5.0/osx-x64/publish/friendly_jigger_mac"
    skip_cleanup: true
    draft: false
    overwrite: false
    on:
      tags: true
