language: csharp
mono: none
dotnet: 3.1
solution: friendly_jigger.sln
script:
  - dotnet restore
  - dotnet publish --self-contained true -c Release -r win10-x64 /p:PublishSingleFile=true -p:PublishReadyToRun=true

deploy:
  provider: releases
  api_key: $DEPLOY_TOKEN
  file: 
    - "./friendly_jigger/bin/Release/netcoreapp3.1/win10-x64/friendly_jigger.exe"
    - "./friendly_jigger/bin/Release/netcoreapp3.1/win10-x64/friendly_jigger.dll"
  skip_cleanup: true
  draft: true
  #on:
  #  tags: true